<div class="row">
    <?
    foreach ($this->articles as $article): ?>
        <div class="col-lg-4">
            <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="140" height="140">
            <h2><?= $article->getMeta()->getName(); ?></h2>
            <p><?= $article->getMeta()->getDescription(); ?></p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
        </div>
    <?php endforeach; ?>
</div>