<div notifications="top right" class="cms-notifications"></div>

<aside class="admin-panel">

    <header class="row admin-heading">
        <h1>ALiEN CMS <small>v 1.0.0a</small></h1>
    </header>

    <section class="row admin-section user-profile">
        <div class="col-xs-2 col-image">
            <img src="/static/profile.jpg" alt="Profile Image" class="img-circle profile-image">
        </div>
        <div class="col-xs-5 col-name">
            <strong>Admin Name</strong>
            <br>Administrator
        </div>
        <div class="col-xs-5 col-buttons">

            <div class="btn-group btn-group-lg" role="group" aria-label="Basic example">
                <button class="btn btn-link">
                    <i class="fa fa-envelope-o text-muted"></i>
                    <span class="label label-pill label-info label-badge">0</span>
                </button>
                <button class="btn btn-link">
                    <i class="fa fa-bell-o active"></i>
                    <span class="label label-pill label-danger label-badge">3</span>
                </button>
                <button class="btn btn-link">
                    <i class="fa fa-sign-out"></i>
                </button>
            </div>

        </div>
    </section>

    <section class="row admin-section page-settings">
        <header>
            <h2>Settings <small>Home Page</small></h2>
        </header>
        <div>
            <div><strong>Link</strong>: # <button class="btn btn-sm">Copy</button></div>
            <div><strong>Status</strong>: <span class="status status-draft">DRAFT</span></div>
            <div><strong>Created</strong>: 7.7.2016</div>
            <div><strong>Last Update</strong>: 7.7.2016</div>
            <div><strong>Language</strong>: SK</div>
            <div><strong>Labels</strong>:
                <ul class="taglist">
                    <li>TAG1</li>
                    <li>TAG2</li>
                    <li>TAG3</li>
                    <li>TAG4</li>
                </ul>
            </div>
        </div>
        <div>
            <h4>Actions</h4>

            <div>
                <button class="btn btn-primary" disabled>
                    Make Home Page
                </button>
            </div>

            <div>
                <button class="btn btn-primary">
                    Save
                </button>
                <button class="btn btn-primary">
                    Clone
                </button>
                <button class="btn btn-primary">
                    Delete
                </button>
            </div>
        </div>
    </section>

    <section class="row global-settings">
        <h2>Global Settings</h2>
        <button class="btn btn-primary">
            Show Settings
        </button>
        <button class="btn btn-primary">
            Need Help?
        </button>
    </section>

</aside>