<aside layout="column" layout-align="start none" ng-cloak>

    <header>
        <h1 class="md-title">ALiEN CMS
            <small>v 1.0.0a</small>
        </h1>
        <loader/>
    </header>

    <acms-login-status></acms-login-status>
    <acms-page-settings></acms-page-settings>

    <section>
        <md-card>
            <md-card-actions layout="row" layout-align="space-around center">
                <md-button class="md-raised md-primary"><i class="fa fa-gears"></i> Show global settings</md-button>
                <md-button class="md-raised md-primary"><i class="fa fa-question-circle"></i> Need Help?</md-button>
            </md-card-actions>
        </md-card>
    </section>

</aside>