<div notifications="top right" class="cms-notifications"></div>

<aside layout="column" layout-align="start none" ng-cloak>

    <header>
        <h1 class="md-title">ALiEN CMS
            <small>v 1.0.0a</small>
        </h1>
        <loader/>
    </header>

    <login-status></login-status>

    <!--<section>-->
        <!--<md-card>-->
            <!--<md-card-title>-->
                <!--<md-card-title-text>-->
                    <!--<span class="md-headline">User Name</span>-->
                    <!--<span class="md-subhead">Administrator</span>-->
                <!--</md-card-title-text>-->
                <!--<md-card-title-media>-->
                    <!--<div class="md-media-sm card-media">-->
                        <!--<img src="/static/profile.jpg" alt="Profile Image" class="img-circle profile-image">-->
                    <!--</div>-->
                <!--</md-card-title-media>-->
            <!--</md-card-title>-->
            <!--<md-card-actions layout="row" layout-align="end center">-->
                <!--<md-button>Messages</md-button>-->
                <!--<md-button>Alerts</md-button>-->
                <!--<md-button>Sign out</md-button>-->
            <!--</md-card-actions>-->
        <!--</md-card>-->
    <!--</section>-->

    <page-settings></page-settings>

    <section>
        <md-card>
            <md-card-actions layout="row" layout-align="space-around center">
                <md-button class="md-raised md-primary"><i class="fa fa-gears"></i> Show global settings</md-button>
                <md-button class="md-raised md-primary"><i class="fa fa-question-circle"></i> Need Help?</md-button>
            </md-card-actions>
        </md-card>
    </section>

</aside>